from tokens.token import Token
from tokens.finals import TipoToken
from tokens.finals import UnknowToken
from tokens.finals import VoidTipoToken
from tokens.finals import UnderlineToken
from tokens.finals import ConstanteToken
from tokens.finals import MainToken
from tokens.finals import RetornoToken
from tokens.finals import IfToken
from tokens.finals import ElseToken
from tokens.finals import PrintToken
from tokens.finals import StringToken
from tokens.finals import CharToken
from tokens.finals import IntToken
from tokens.finals import FloatToken
from tokens.finals import BoolToken
