from identifiers.identifier import Identifier
from identifiers.indetifier_all import IndetifierAll
from identifiers.tipo_indentifier import TipoIndetifier
from identifiers.void_tipo_identifier import VoidTipoIdentifier