from identifiers.identifier import Identifier
from identifiers.identifier_all import IdentifierAll

from identifiers.finals import IDENTIFY_ALL_FINALS
from identifiers.finals import IDENTIFY_WITHOUT_UNKNOWN
from identifiers.finals import TipoIndetifier
from identifiers.finals import UnknowIdentifier
from identifiers.finals import VoidTipoIdentifier
from identifiers.finals import UnderlineIdentifier
from identifiers.finals import ConstanteIdentifier
from identifiers.finals import RetornoIdentifier
from identifiers.finals import IfIdentifier
from identifiers.finals import ElseIdentifier
from identifiers.finals import PrintIdentifier
from identifiers.finals import StringIdentifier
from identifiers.finals import CharIdentifier
from identifiers.finals import IntIdentifier
from identifiers.finals import FloatIdentifier
from identifiers.finals import BoolIdentifier
