import re

from categories import Categories


REGEX = {
    Categories.BOOL: r"bool",
    Categories.CHAR: r"char",
    Categories.INT: r"int",
    Categories.FLOAT: r"float",
    Categories.STRING: r"string",
    Categories.VOID: r"void",
    Categories.UNDERLINE: r"_",
    Categories.CONSTANTE: r"const",
    Categories.MAIN: r"main",
    Categories.RETORNO: r"return",
    Categories.IF: r"if",
    Categories.ELSE: r"else",
    Categories.PRINT: r"print",
    Categories.LITERAL_STRING: r"\"(([\w\s\[\]{}()<(>)'=|.,;!?])|(\"))*\"",
    Categories.LITERAL_CHAR: r"'([\w\s\[\]{}()<(>)\"=|.,;!?])|(\\')'",
    Categories.LITERAL_INT: r"\d+",
    Categories.LITERAL_FLOAT: r"\d+\.\d+",
    Categories.LITERAL_BOOL: r"true|false",
    Categories.VIRGULA: r"\,",
    Categories.PONTO_VIRGULA: r";",
    Categories.ABRIR_CHAVE: r"\[",
    Categories.FECHAR_CHAVE: r"\]",
    Categories.ABRIR_COLCHETE: r"\{",
    Categories.FECHAR_COLCHETE: r"\}",
    Categories.ABRIR_PARENTESES: r"\(",
    Categories.FECHAR_PARENTESES: r"\)",
    Categories.WHILE: r"while",
    Categories.SCAN: r"scan",
    Categories.FOR: r"for",
    Categories.OPERADOR_CONCATENACAO: r"::",
    Categories.OPERADOR_OU: r"\|\|",
    Categories.OPERADOR_E: r"&&",
    Categories.OPERADOR_MAIOR_IGUAL: r">=",
    Categories.OPERADOR_MENOR_IGUAL: r"<=",
    Categories.OPERADOR_MAIOR: r">",
    Categories.OPERADOR_MENOR: r"<",
    Categories.OPERADOR_IGUAL: r"=",
    Categories.OPERADOR_ADICAO: r"\+",
    Categories.OPERADOR_SUBTRACAO: r"-",
    Categories.OPERADOR_MULTIPLICACAO: r"\*",
    Categories.OPERADOR_DIVISAO: r"/",
    Categories.OPERADOR_RESTO: r"%",
    Categories.OPERADOR_NEGACAO: r"!",
    Categories.IDENTIFICADOR: r"_{0,1}[A-Za-z0-9_]+",
    Categories.DOISPONTOS: r":"
}
