from identifiers.finals.identifier_finals import IDENTIFY_ALL_FINALS
from identifiers.finals.identifier_without_unknow import IDENTIFY_WITHOUT_UNKNOW
from identifiers.finals.letra_maiscula_identifier import LetraMaiusculaIdentifier
from identifiers.finals.letra_minuscula_identifier import LetraMinusculaIdentifier
from identifiers.finals.simbolos_identifier import SimboloIdentifier
from identifiers.finals.tipo_indentifier import TipoIndetifier
from identifiers.finals.unknow_identifier import UnknowIdentifier
from identifiers.finals.void_tipo_identifier import VoidTipoIdentifier
