from tokens.finals.tipo_token import TipoToken
from tokens.finals.unknow_token import UnknowToken
from tokens.finals.void_tipo_token import VoidTipoToken
from tokens.finals.underline_tokens import UnderlineToken
from tokens.finals.main_token import MainToken
from tokens.finals.constante_token import ConstanteToken
from tokens.finals.retorno_token import RetornoToken
from tokens.finals.if_token import IfToken
from tokens.finals.else_token import ElseToken
from tokens.finals.print_token import PrintToken
from tokens.finals.string_token import StringToken
from tokens.finals.char_token import CharToken
from tokens.finals.int_token import IntToken
from tokens.finals.float_token import FloatToken
from tokens.finals.bool_token import BoolToken
from tokens.finals.igual_token import IgualToken
from tokens.finals.virgula_token import VirgulaToken
from tokens.finals.ponto_virgula_token import PontoVirgulaToken
from tokens.finals.abrir_chave_token import AbrirChaveToken
from tokens.finals.fechar_chave import FecharChaveToken
from tokens.finals.abrir_colchete_token import AbrirColcheteToken
from tokens.finals.fechar_colchete_token import FecharColcheteToken
from tokens.finals.abrir_parenteses_token import AbrirParentesesToken
from tokens.finals.fechar_parenteses_token import FecharParentesesToken
from tokens.finals.while_token import WhileToken
from tokens.finals.scan_token import ScanToken
from tokens.finals.identificador import IdentificadorToken
from tokens.finals.operador_concatenacao import OperadorConcatenacaoToken
from tokens.finals.operador_ou import OperadorOuTOken
from tokens.finals.operador_e import OperadorEToken
from tokens.finals.operador_maior import OperadorMaiorToken
from tokens.finals.operador_menor import OperadorMenorToken
from tokens.finals.operador_maior_igual import OperadorMaiorIgualToken
from tokens.finals.operador_menor_igual import OperadorMenorIgualToken
from tokens.finals.operador_igual import OperadorIgualToken
from tokens.finals.operador_adicao import OperadorAdicaoToken
from tokens.finals.operador_subtracao import OperadorSubtracaoToken
from tokens.finals.operador_multiplicacao import OperadorMultiplicacaoToken
from tokens.finals.operador_divisao import OperadorDivisaoToken
from tokens.finals.operador_resto import OperadorRestoToken
from tokens.finals.operador_negacao import OperadorNegacaoToken